export const site = {
  name: "Paulo Freitas",
  title: "Product Designer + Engineer",
  x: "https://x.com/freitaspauloo",
  tagline: "I design complex product surfaces and ship them in code.",
  domain: "paulo.dudesign.us",
  url: "https://paulo.dudesign.us",
  email: "hello@dudesign.us",
  linkedin: "https://www.linkedin.com/in/freitas-pauloo",
  github: "https://github.com/freitaspauloo",
  credibility: ["Audi", "Samsung", "3M", "Ford", "Sony + Honda", "Costco"],
  skills: [
    "Product UX & UI design",
    "Interaction design",
    "Visual design & typography",
    "Design systems",
    "User research & testing",
    "AI & agent UX",
    "Trust & accessibility UX",
    "Prototyping in code",
    "B2B SaaS & enterprise",
    "Cross-functional leadership",
  ],
  builtWith: "Designed and built by me in Next.js + Cursor",
} as const;
